#! /usr/bin/env ruby
require 'optparse'
require 'torchat'

require 'eventmachine'
require 'em-websocket'
require 'evma_httpserver'

require 'json'
require 'erb'
require 'mimetype_fu'

options = {}

OptionParser.new do |o|
	options[:web] = {
		host: '127.0.0.1',
		port: 11110
	}

	options[:websocket] = {
		host: '127.0.0.1',
		port: 11111
	}

	o.on '-p', '--profile NAME', 'the profile name' do |name|
		options[:profile] = name
	end

	o.on '-c', '--config PATH', 'the path to the config file' do |path|
		options[:config] = path
	end

	o.on '-t', '--tor', 'enable automatic generation and run of Tor' do
		options[:tor] = true
	end

	o.on '-l', '--listen HOST:PORT...', Array, 'the host and port to listen on' do |value|
		host, port = value.first.split(':')

		options[:web][:host] = host      unless host.empty?
		options[:web][:port] = port.to_i unless port.empty?

		host, port = value.last.split(':')

		options[:websocket][:host] = host      unless host.empty?
		options[:websocket][:port] = port.to_i unless port.empty?
	end

	o.on '-s', '--ssl KEY:CERT', 'the private key and cert files' do |path|
		options[:ssl] = { key: path.split(':').first, cert: path.split(':').last }
	end

	o.on '-P', '--password PASSWORD' do |password|
		options[:password] = password
	end

	o.on '-o', '--online' do
		options[:online] = true
	end

	o.on '-d', '--debug [LEVEL=1]', 'enable debug mode' do |value|
		ENV['DEBUG'] = value || ?1
	end
end.parse!

class TorchatWebUI
	class WebsocketConnection < EM::WebSocket::Connection
		attr_accessor :daemon, :host, :port, :ssl

		def authorized?; @authorized;        end
		def authorize!;  @authorized = true; end

		def post_init
			onmessage {|msg|
				daemon.process self, msg
			}
		end

		def send_message (type, arguments)
			send [type, arguments].to_json
		end

		def unbind
			@daemon.connections.delete self
		end
	end

	class WebConnection < EM::Connection
		include EM::HttpServer

		attr_accessor :daemon, :ssl

		def post_init
			super

			no_environment_strings
		end

		def process_http_request
			response = EM::DelegatedHttpResponse.new(self)

			if @http_path_info == '/'
				response.status = 200
				response.content_type 'text/html'

				listens_on = daemon.listens_on

				response.content = ERB.new(File.read('public/index.erb')).result(binding)
			else
				response.content_type File.mime_type?("public#{@http_path_info}")

				unless File.exists? "public#{@http_path_info}"
					response.status = 404
				else
					response.status = 200
					response.content = File.open("public#{@http_path_info}", "r")
				end
			end

			response.send_response
		end
	end

	attr_reader   :password, :connections, :listens_on
	attr_accessor :profile, :tor

	def initialize (password = nil, file_transfer_ports = [])
		@password    = password
		@buddies     = []
		@connections = []
		@pings       = Hash.new { |h, k| h[k] = {} }
		@listens_on  = {}

		yield self if block_given?
	end

	def start (web, websocket, ssl = nil)
		return if @started

		@started   = true

		listens_on[:web]       = web
		listens_on[:websocket] = websocket

		@websocket = EM.start_server websocket[:host], websocket[:port], WebsocketConnection, websocket do |conn|
			@connections << conn

			conn.daemon = self
			conn.host   = host
			conn.port   = port
			conn.ssl    = ssl

			unless @password
				conn.authorize!
			end
		end

		@web = EM.start_server web[:host], web[:port], WebConnection do |conn|
			conn.daemon = self
			conn.ssl    = ssl
		end
	end

	def stop
		EM.stop_server @websocket
		EM.stop_server @web

		profile.stop

		tor.stop if tor
	end

	def process (connection, line)
		command, arguments = JSON.parse(line)

		case command.downcase.to_sym
		when :pass
			if !@password || @password == arguments.first
				connection.authorize!
				connection.send_message :authorized, profile.session.id
			end

			return
		end

		unless connection.authorized?
			connection.send_message :unauthorized, command
			return
		end

		case command.downcase.to_sym
		when :whoami
			connection.send_message :whoami, profile.id

		when :list
			connection.send_message :list, profile.buddies.keys

		when :remove
			profile.buddies.remove arguments

		when :add
			if arguments['temporary']
				profile.buddies.add_temporary arguments['id']
			else
				profile.buddies.add arguments['id']
			end

		when :typing
			if buddy = profile.buddies[arguments['id']]
				buddy.send_typing(arguments['mode'])
			end

		when :status
			if Torchat.normalize_id(arguments, true)
				if buddy = profile.buddies[arguments]
					connection.send_message :status, id: buddy.id, status: buddy.status
				end
			else
				profile.status = arguments
			end

		when :client
			if buddy = profile.buddies[arguments]
				if buddy.client.name
					connection.send_message :client_name, id: buddy.id, name: buddy.client.name
				end

				if buddy.client.version
					connection.send_message :client_version, id: buddy.id, version: buddy.version
				end
			end

		when :name
			if arguments && Torchat.normalize_id(arguments, true)
				if buddy = profile.buddies[arguments]
					connection.send_message :name, id: buddy.id, name: buddy.name
				end
			else
				profile.name = arguments
			end

		when :description
			if arguments && Torchat.normalize_id(arguments, true)
				if buddy = profile.buddies[rest]
					connection.send_message :description, id: buddy.id, description: buddy.description
				end
			else
				profile.description = arguments
			end

		when :message
			profile.send_message_to arguments['id'], arguments['message']

		when :block
			profile.buddies[arguments].block!

		when :allow
			profile.buddies[arguments].allow!

		when :broadcast
			profile.send_broadcast arguments

		when :groupchats
			connection.send_message :groupchats, profile.group_chats.keys

		when :groupchat_participants
			if group_chat = profile.group_chats[arguments]
				connection.send_message :groupchat_participants, id: group_chat.id, participants: group_chat.participants.keys
			end

		when :groupchat_invite
			if arguments['groupchat_id']
				if (buddy = profile.buddies[arguments['buddy_id']]) && (group_chat = profile.group_chats[arguments['groupchat_id']])
					group_chat.invite(buddy)
				end
			else
				if buddy = profile.buddies[arguments['buddy_id']]
					profile.group_chats.create.invite(buddy)
				end
			end

		when :groupchat_leave
			if group_chat = profile.group_chats[arguments['id']]
				group_chat.leave arguments['reason']
			end

		when :groupchat_message
			group_chat, message = rest.split ' ', 2

			if group_chat = profile.group_chats[arguments['id']]
				group_chat.send_message arguments['message']
			end

		when :latency
			if (buddy = profile.buddies[arguments['id']]) && buddy.supports?(:latency)
				@pings[id][buddy.latency.ping!.id] = [Time.now, arguments['payload']]
			end

		else
			connection.send_message :unimplemented, command
		end
	rescue => e
		Torchat.debug e
	end

	def received_packet (packet)
		return unless @buddies.include? packet.from

		if packet.type == :message
			send_everyone :message, id: packet.from.id, message: packet.to_s
		elsif packet.type == :status
			send_everyone :status, id: packet.from.id, status: packet.to_s
		elsif packet.type == :client
			send_everyone :client_name, id: packet.from.id, name: packet.to_s
		elsif packet.type == :version
			send_everyone :client_version, id: packet.from.id, version: packet.to_s
		elsif packet.type == :profile_name && !packet.nil?
			send_everyone :name, id: packet.from.id, name: packet.to_s
		elsif packet.type == :profile_text && !packet.nil?
			send_everyone :description, id: packet.from.id, description: packet.to_s
		elsif packet.type == :remove_me
			send_everyone :remove, packet.from.id
		end
	end

	def file_transfer (what, file_transfer, *args)
		if what == :start

		elsif what == :stop

		elsif what == :complete

		end
	end

	def typing (buddy, mode)
		send_everyone :typing, id: buddy.id, mode: mode
	end

	def broadcast (message)
		send_everyone :broadcast, message
	end

	def group_chat (what, group_chat, buddy = nil, *args)
		if what == :create
			send_everyone :groupchat_create, group_chat.id
		elsif what == :invite
			send_everyone :groupchat_invite, groupchat_id: group_chat.id, buddy_id: buddy.id
		elsif what == :join
			send_everyone :groupchat_join, groupchat_id: group_chat.id, buddy_id: buddy.id, invitor_id: args.first
		elsif what == :joined
			send_everyone :groupchat_joined, group_chat.id
			send_everyone :groupchat_participants, id: group_chat.id, participants: group_chat.participants.keys
		elsif what == :leave
			send_everyone :groupchat_leave, groupchat_id: group_chat.id, buddy_id: buddy.id, reason: args.first
		elsif what == :left
			send_everyone :groupchat_left, id: group_chat.id, reason: args.first
		elsif what == :message
			send_everyone :groupchat_message, groupchat_id: group_chat.id, buddy_id: buddy.id, message: args.first
		elsif what == :destroy
			send_everyone :groupchat_destroy, group_chat.id
		end
	end

	def latency (buddy, amount, id)
		send_everyone :latency, id: buddy.id, payload: @pings[buddy.id].delete(id).last
	end

	def cleanup!
		@pings.each {|id, pings|
			pings.reject! {|time, payload|
				(Time.now - time).to_i >= 80
			}
		}

		@pings.reject!(&:empty?)
	end

	def connected?; @connected; end

	def connected (buddy)
		@buddies << buddy

		send_everyone :connected, id: buddy.id

		if buddy.name
			send_everyone :name, id: buddy.id, name: buddy.name
		end

		if buddy.description
			send_everyone :description, id: buddy.id, description: buddy.description
		end

		if buddy.client.name
			send_everyone :client_name, id: buddy.id, name: buddy.client.name
		end

		if buddy.client.version
			send_everyone :client_version, id: buddy.id, version: buddy.client.version
		end
	end

	def disconnected (buddy)
		return unless @buddies.include? buddy

		send_everyone :disconnected, buddy.id

		@buddies.delete buddy
	end

	def removed (buddy)
		return unless @buddies.include? buddy

		send_everyone :remove, buddy.id
	end

	def send_everyone (type, arguments = nil, even_unauthorized = false)
		@connections.each {|connection|
			next unless connection.authorized? || even_unauthorized

			connection.send_message type, arguments
		}
	end
end

EM.run {
	TorchatWebUI.new(options[:password]) {|d|
		d.profile = options[:config] ? Torchat.new(options[:config]) : Torchat.profile(options[:profile])

		puts 'torchat-web-ui starting...'

		if options[:tor]
			d.profile.tor.file = 'torrc.txt'

			d.profile.tor.start "#{d.profile.path || '~/.torchat'}/Tor", -> {
				abort 'could not load the onion id' if 20.times {
					break if File.exists? 'hidden_service/hostname'

					sleep 1
				}
			}, -> {
				abort 'tor exited with errors'
			}
		end

		unless d.profile.config['id']
			if d.profile.path
				if File.readable?("#{d.profile.path}/Tor/hidden_service/hostname")
					d.profile.config['id'] = File.read("#{d.profile.path}/Tor/hidden_service/hostname")[/^(.*?)\.onion/, 1]
				end
			end or abort 'could not deduce the onion id'
		end

		puts "torchat-web-ui started for #{d.profile.config['id']} on http://#{options[:web][:host]}:#{options[:web][:port]}"

		%w[INT KILL].each {|sig|
			trap sig do
				puts 'torchat-web-ui stopping...'

				d.stop

				EM.stop_event_loop
			end
		}

		d.profile.start {|s|
			s.on :connect_to do |e|
				Torchat.debug "connecting to #{e.address}:#{e.port}"
			end

			s.on :connect_failure do |e|
				Torchat.debug "#{e.buddy.id} failed to connect"
			end

			s.on :connect do |e|
				Torchat.debug "#{e.buddy.id} connected"
			end

			s.on :verify do |e|
				Torchat.debug "#{e.buddy.id} has been verified"
			end

			s.on :ready do |e|
				d.connected e.buddy
			end

			s.on :remove_buddy do |e|
				d.removed e.buddy
			end

			s.on :disconnect do |e|
				Torchat.debug "#{e.buddy.id} disconnected"

				d.disconnected e.buddy
			end

			s.on_packet do |e|
				d.received_packet e.packet unless e.packet.extension
			end

			s.on :file_transfer_start do |e|
				d.file_transfer :start, e.file_transfer
			end

			s.on :file_transfer_stop do |e|
				d.file_transfer :stop, e.file_transfer
			end

			s.on :file_transfer_complete do |e|
				d.file_transfer :complete, e.file_transfer
			end

			s.on :typing do |e|
				d.typing e.buddy, e.mode
			end

			s.on :broadcast do |e|
				d.broadcast e.message
			end

			s.on :group_chat_create do |e|
				d.group_chat :create, e.group_chat
			end

			s.on :group_chat_invite do |e|
				d.group_chat :invite, e.group_chat, e.buddy
			end

			s.on :group_chat_join do |e|
				if e.buddy
					d.group_chat :join, e.group_chat, e.buddy, e.invited_by
				else
					d.group_chat :joined, e.group_chat, nil, e.invited_by
				end
			end

			s.on :group_chat_message do |e|
				d.group_chat :message, e.group_chat, e.buddy, e.message
			end

			s.on :group_chat_leave do |e|
				if e.buddy
					d.group_chat :leave, e.group_chat, e.buddy, e.reason
				else
					d.group_chat :left, e.group_chat, nil, e.reason
				end
			end

			s.on :group_chat_destroy do |e|
				d.group_chat :destroy, e.group_chat
			end

			s.on :latency do |e|
				d.latency e.buddy, e.amount, e.id
			end

			s.online! if options[:online]
		}

		EM.add_periodic_timer 60 do
			d.cleanup!
		end
	}.start(options[:web], options[:websocket], options[:ssl])
}
